"""Generates docs/msk-kikinda/MODEL-OUTPUTS.md — every table cited in STUDY.md."""
import sys, os, io
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from msk_model import *

OUT = io.StringIO()
def w(s=""): OUT.write(s + "\n")
def pct(x): return f"{x:.1%}" if x is not None else "n/a"
def num(x, d=1): return f"{x:,.{d}f}" if x is not None else "n/a"

BASE = Project()

def rec(cy=10, cap=2.10, **kw):
    d = dict(senior_pct=0.65, senior_rate=0.062, senior_tenor=12, senior_grace=2,
             investor_equity=42.0, investor_shl=58.0, shl_rate=0.09,
             shl_pik_years=1, shl_bullet_year=9,
             founder_econ=0.60, founder_votes=0.60,
             call_year=cy, call_target_irr=0.14, call_moic_floor=1.60,
             call_moic_cap=cap, call_formula="capped")
    d.update(kw)
    return Structure("REC", "Recommended structure", **d)

w("# MSK Kikinda — model outputs")
w()
w("_Generated by `model/build_outputs.py`. Every figure in `STUDY.md` traces to a table here._")
w()
w("All amounts EUR million unless stated. Base case: capex 200, full-ramp EBITDA 46, "
  "COD start of Year 3, exit multiple 5.5x EV/EBITDA, Serbian CIT 15%.")
w()
w("> **These operating assumptions are illustrative placeholders for structuring, not forecasts.** "
  "EBITDA of 46 has *not* been validated by any engineering study. Table 12 shows what happens "
  "when it is wrong, and that is the table that matters most.")
w()

# ---------------------------------------------------------------- Table 1
w("## Table 1 — The ten candidate structures (base case)")
w()
w("| # | Structure | Senior | Inv. equity | Inv. SHL | Inv. cash | Founder econ | Founder votes | Min DSCR | Inv. IRR (hold to Y15) | Inv. MOIC | Founder wealth Y15 |")
w("|---|-----------|-------:|------:|------:|------:|------:|------:|------:|------:|------:|------:|")
rows_s = []
for s in structures():
    r = run(BASE, s)
    rows_s.append((s, r))
    w(f"| {s.name} | {s.label} | {num(r['senior'])} | {num(r['investor_equity'])} | "
      f"{num(r['investor_shl'])} | {num(r['investor_cash'])} | {s.founder_econ:.0%} | "
      f"{s.founder_votes:.0%} | {num(r['min_dscr'],2)} | {pct(r['inv_irr_hold'])} | "
      f"{num(r['inv_moic_hold'],2)} | {num(r['founder_wealth'](15, False))} |")
w()
w("**Reading.** No structure on this asset produces a classic private-equity minority return. "
  "The best investor IRR available across all ten (Structure F, 12% subordinated debt + warrants, "
  "and Structure G, maximum leverage) sits in the low-to-mid teens. Fighting over 51% vs 60% moves "
  "the investor's IRR by roughly 4 points and the founder's terminal wealth by far more — but it "
  "never turns this into a 20% IRR deal. That is a fact about the asset, not about the split.")
w()

# ---------------------------------------------------------------- Table 2
w("## Table 2 — Recommended structure: capital stack")
w()
R = run(BASE, rec())
w(f"| Item | Amount | % of total |")
w(f"|------|-------:|-----------:|")
tot = R['funding_need']
w(f"| Modernisation capex | {num(BASE.total_capex)} | {BASE.total_capex/tot:.0%} |")
w(f"| Fees and financing costs (2.5%) | {num(0.025*BASE.total_capex)} | {0.025*BASE.total_capex/tot:.0%} |")
w(f"| Initial working capital | {num(BASE.working_capital)} | {BASE.working_capital/tot:.0%} |")
w(f"| Debt service reserve (6 months) | {num(R['dsra'])} | {R['dsra']/tot:.0%} |")
w(f"| **Total funding need** | **{num(tot)}** | **100%** |")
w()
w(f"| Source | Amount | % of need |")
w(f"|--------|-------:|----------:|")
w(f"| Senior / ECA-backed project debt | {num(R['senior'])} | {R['gearing']:.0%} |")
w(f"| Investor shareholder loan (9%) | {num(R['investor_shl'])} | {R['investor_shl']/tot:.0%} |")
w(f"| Investor ordinary equity | {num(R['investor_equity'])} | {R['investor_equity']/tot:.0%} |")
w(f"| Founder cash | 0.0 | 0% |")
w(f"| **Total** | **{num(tot)}** | **100%** |")
w()
w(f"Sizing constraint: **{R['senior_binding']}**. Maximum debt a {rec().dscr_floor:.2f}x minimum DSCR "
  f"would support is {num(R['dscr_max_debt'])} ({R['dscr_max_debt']/tot:.0%} of need); the structure "
  f"deliberately stops at {R['gearing']:.0%}. Minimum DSCR achieved: **{num(R['min_dscr'],2)}x**, "
  f"distribution lock-up years: {R['lockup_years']}.")
w()
w("Acquisition price for the MSK shares (illustrative 40) sits **outside** this stack — see Table 8.")
w()

# ---------------------------------------------------------------- Table 3
w("## Table 3 — Recommended structure: annual cash flow and waterfall")
w()
w("| Yr | EBITDA | Tax | CFADS | Sen. int | Sen. prin | Sen. bal | DSCR | SHL bal | SHL cash | Distrib. | To founder | To investor |")
w("|---:|-------:|----:|------:|---------:|----------:|---------:|-----:|--------:|---------:|---------:|-----------:|------------:|")
for row in R['rows']:
    w(f"| {row['year']} | {num(row['ebitda'])} | {num(row['tax'])} | {num(row['cfads'])} | "
      f"{num(row['s_int'])} | {num(row['s_prin'])} | {num(row['s_bal'])} | "
      f"{num(row['dscr'],2) if row['dscr'] else '—'} | {num(row['shl_bal'])} | "
      f"{num(row['shl_int']+row['shl_prin'])} | {num(row['div_total'])} | "
      f"{num(row['div_founder'])} | {num(row['div_investor'])} |")
w()
w("Note Years 5–8: ordinary distributions are near zero because the shareholder loan is amortising. "
  "This is the price of returning the investor's cash early, and it is deliberate — see Table 6.")
w()

# ---------------------------------------------------------------- Table 4
w("## Table 4 — Investor return, by exit route")
w()
w("| Exit route | Investor IRR | Investor MOIC |")
w("|------------|-------------:|--------------:|")
w(f"| Hold to Year 15, sale at 5.5x | {pct(R['inv_irr_hold'])} | {num(R['inv_moic_hold'],2)} |")
for cy in (8, 10, 12):
    rr = run(BASE, rec(cy=cy))
    w(f"| Founder call exercised Year {cy} (2.10x cap) | {pct(rr['inv_irr_call'])} | {num(rr['inv_moic_call'],2)} |")
w()
w("Decomposition of the investor's return in the hold case (recommended structure):")
w()
inv_eq_cash = sum(r['div_investor'] for r in R['rows'])
inv_shl_cash = sum(r['shl_int'] + r['shl_prin'] for r in R['rows'])
term = max(0.0, R['equity_value'](15)) * (1 - 0.60)
w("| Component | Cash to investor |")
w("|-----------|-----------------:|")
w(f"| Shareholder loan interest and principal | {num(inv_shl_cash)} |")
w(f"| Ordinary dividends (40% share) | {num(inv_eq_cash)} |")
w(f"| Terminal equity value (40% of Y15 equity) | {num(term)} |")
w(f"| **Total in** | **{num(inv_shl_cash+inv_eq_cash+term)}** |")
w(f"| Total invested | {num(R['investor_cash'])} |")
w()
w("**No double counting:** the shareholder loan is repaid in full by Year 8 and its balance is "
  "deducted from equity value at every valuation date, so loan repayment and equity upside are "
  "disjoint claims on the same cash.")
w()

# ---------------------------------------------------------------- Table 5
w("## Table 5 — Founder economics")
w()
w("| Case | Wealth Y5 | Wealth Y10 | Wealth Y15 |")
w("|------|----------:|-----------:|-----------:|")
w(f"| Hold 60%, no call | {num(R['founder_wealth'](5,False))} | {num(R['founder_wealth'](10,False))} | {num(R['founder_wealth'](15,False))} |")
for cy, cap in ((10, 2.10), (11, 2.25), (12, 2.00)):
    rr = run(BASE, rec(cy=cy, cap=cap))
    w(f"| Call at Y{cy}, {cap:.2f}x MOIC cap | {num(rr['founder_wealth'](5,True))} | "
      f"{num(rr['founder_wealth'](10,True))} | {num(rr['founder_wealth'](15,True))} |")
w()
w("Founder wealth = (share of equity value at 5.5x EV/EBITDA) + (cumulative distributions received) "
  "− (outstanding acquisition obligation) − (debt raised to fund any call).")
w()
w("Wealth at Year 5 is thin in every case: the asset is still levered, the acquisition obligation is "
  "still outstanding, and distributions are locked up. **Any structure requiring the founder to show "
  "personal liquidity before Year 8 will break.**")
w()

# ---------------------------------------------------------------- Table 6
w("## Table 6 — Call option: formula comparison (the single most important table)")
w()
nocall_w = run(BASE, rec())['founder_wealth'](15, False)
w(f"Benchmark — founder simply holds 60% and never exercises: **wealth Y15 = {num(nocall_w)}**.")
w()
w("| Formula | Call yr | Price | FMV of investor position | Premium to FMV | Fundable by refi? | Investor IRR | Investor MOIC | Founder wealth Y15 | vs. holding |")
w("|---------|--------:|------:|------:|------:|:--:|------:|------:|------:|------:|")
for formula, lbl in (("irr", "IRR ratchet 14%"), ("greater", "Greater of 14% IRR / 1.6x"),
                     ("capped", "Greater of, capped at 2.10x"), ("fmv", "Fair market value"),
                     ("moic", "1.6x MOIC only")):
    for cy in (8, 10, 12):
        rr = run(BASE, rec(cy=cy, call_formula=formula))
        c, f = rr['call'], rr['call_fund']
        prem = (c['chosen'] / c['fmv_share'] - 1) if c['fmv_share'] > 0 else 0
        dw = rr['founder_wealth'](15, True) - nocall_w
        w(f"| {lbl} | {cy} | {num(c['chosen'])} | {num(c['fmv_share'])} | {prem:+.0%} | "
          f"{'yes' if f['ok'] else 'NO'} | {pct(rr['inv_irr_call'])} | {num(rr['inv_moic_call'],2)} | "
          f"{num(rr['founder_wealth'](15,True))} | {dw:+.1f} |")
w()
w("**Three conclusions the founder must internalise:**")
w()
w("1. An **IRR-ratchet call gets more expensive every year** (106 → 127 between Y8 and Y12) while a "
  "**MOIC call gets cheaper every year** (59 → 48), because interim cash received reduces the MOIC "
  "top-up but the IRR clock keeps compounding. These move in opposite directions. The founder wants "
  "MOIC; the investor wants IRR.")
w("2. A pure IRR-ratchet call is priced at a **60–75% premium to the fair value of what is being "
  "bought**, and is **not fundable** by refinancing at 3.5x EBITDA at any point in the model. It is "
  "not a founder protection — it is an investor protection the founder has been persuaded to want.")
w("3. The only designs that are simultaneously fundable and accretive are **MOIC-capped calls "
  "exercised late (Y10+)**. They deliver the investor ~10.5–11.5% IRR at a 2.0–2.25x multiple.")
w()

# ---------------------------------------------------------------- Table 7
w("## Table 7 — Call option: the viability frontier")
w()
w("Searching (MOIC cap x call year) for a design that is *simultaneously* (a) ≥12% investor IRR, "
  "(b) fundable by refinancing at 3.5x EBITDA, and (c) better for the founder than not exercising:")
w()
w("| MOIC cap | Call yr | Price | Investor IRR | Fundable | Founder wealth Y15 | vs. holding | All three? |")
w("|---------:|--------:|------:|------:|:--:|------:|------:|:--:|")
any_viable = False
for cap in (2.00, 2.10, 2.25, 2.40):
    for cy in (9, 10, 11, 12):
        rr = run(BASE, rec(cy=cy, cap=cap))
        c, f = rr['call'], rr['call_fund']
        wl = rr['founder_wealth'](15, True)
        ok = f['ok'] and (rr['inv_irr_call'] or 0) >= 0.12 and wl > nocall_w
        any_viable = any_viable or ok
        w(f"| {cap:.2f}x | {cy} | {num(c['chosen'])} | {pct(rr['inv_irr_call'])} | "
          f"{'yes' if f['ok'] else 'no'} | {num(wl)} | {wl-nocall_w:+.1f} | {'**YES**' if ok else 'no'} |")
w()
if not any_viable:
    w("**No combination clears all three tests in the base case.** The call option cannot be both "
      "cheap enough to be worth exercising and rich enough to satisfy a 12% investor hurdle, because "
      "the asset does not grow fast enough to outrun the investor's required return. The call is "
      "therefore worth negotiating as a **ceiling on the investor's outcome**, not as a wealth "
      "engine — and it only becomes genuinely accretive if the project outperforms (Table 7b).")
w()
w("### Table 7b — When the call *does* create value: sensitivity to actual EBITDA delivered")
w()
w("The MOIC-capped call price is fixed by the investor's cash flows, not by how well the plant does. "
  "So every euro of outperformance accrues to the founder through the call:")
w()
w("| Actual full-ramp EBITDA | Call price (2.10x cap, Y10) | FMV of investor position | Founder gain from exercising |")
w("|---:|---:|---:|---:|")
for e in (30, 40, 46, 55, 65, 80):
    pr = replace(BASE, ebitda_full=float(e))
    rr = run(pr, rec(cy=10))
    c = rr['call']
    gain = rr['founder_wealth'](15, True) - rr['founder_wealth'](15, False)
    w(f"| {e} | {num(c['chosen'])} | {num(c['fmv_share'])} | {gain:+.1f} |")
w()
w("This is the real case for the call option: it is a **cheap option on the founder's own execution**. "
  "It costs little if the plant performs to plan and pays handsomely if the founder beats plan. "
  "Price it on MOIC, cap it, and exercise late.")
w()

# ---------------------------------------------------------------- Table 8
w("## Table 8 — Acquisition price: where should the 40 sit?")
w()
w("| Option | Cash cost to founder pre-Y8 | Effect on ProjectCo DSCR | Investor reaction | Verdict |")
w("|--------|---:|---|---|---|")
w("| Founder pays cash at closing | 40 | none | neutral | **Rejected** — founder has no 40 |")
w("| ProjectCo pays from investor capital | 0 | reduces capex budget by 40 | investor funds an asset it only gets 40% of | **Rejected** — worst outcome for founder's share |")
w("| ProjectCo pays, charged to founder via distribution waterfall | 0 up front | none (paid below senior) | acceptable | **Workable fallback** |")
w("| Seller credit from State/Srbijagas, HoldCo-level, serviced from founder distributions | 0 | **none — sits outside ProjectCo** | best; keeps ProjectCo clean | **Recommended** |")
w("| Contingent consideration / earn-out on restart milestones | 0 | none | best; aligns state with delivery | **Recommended add-on** |")
w()
rw = [r for r in R['rows']]
w(f"Modelled as a {BASE.acq_deferred_years}-year seller credit at {BASE.acq_rate:.0%}, serviced "
  f"exclusively from the founder's share of distributions. Outstanding balance by year:")
w()
w("| Yr | " + " | ".join(str(r['year']) for r in rw[:9]) + " |")
w("|---|" + "---|"*9 + "")
w("| Acquisition balance | " + " | ".join(num(r['acq_bal']) for r in rw[:9]) + " |")
w()

# ---------------------------------------------------------------- Table 9-11 sensitivities
w("## Table 9 — Sensitivity: total capex")
w()
w("| Capex | Funding need | Senior debt | Investor cash | Min DSCR | Inv. IRR | Founder wealth Y15 |")
w("|---:|---:|---:|---:|---:|---:|---:|")
for cx in (150, 175, 200, 225, 250, 300):
    pr = replace(BASE, capex=float(cx))
    rr = run(pr, rec())
    w(f"| {cx} | {num(rr['funding_need'])} | {num(rr['senior'])} | {num(rr['investor_cash'])} | "
      f"{num(rr['min_dscr'],2)} | {pct(rr['inv_irr_hold'])} | {num(rr['founder_wealth'](15,False))} |")
w()
w("**The capex number dominates everything.** At 150 the deal is comfortably financeable (DSCR 2.09x, "
  "investor IRR 16.3%) and the founder ends at 259. From 250 upward the DSCR test forces the debt down, "
  "so the investor's cheque *grows* while its return collapses — at 300 the investor is asked for 181 to "
  "earn 4.5%, which no one funds. Establishing the real capex before signing any term sheet is worth "
  "more than every basis point of negotiation on the split.")
w()

w("## Table 10 — Sensitivity: senior debt share")
w()
w("| Senior share | Senior debt | Investor cash | Min DSCR | Inv. IRR | Founder wealth Y15 | Financeable? |")
w("|---:|---:|---:|---:|---:|---:|:--:|")
for sp in (0.40, 0.50, 0.60, 0.65, 0.70, 0.75):
    rr = run(BASE, rec(senior_pct=sp))
    fin = rr['min_dscr'] and rr['min_dscr'] >= 1.30
    w(f"| {sp:.0%} | {num(rr['senior'])} | {num(rr['investor_cash'])} | {num(rr['min_dscr'],2)} | "
      f"{pct(rr['inv_irr_hold'])} | {num(rr['founder_wealth'](15,False))} | {'yes' if fin else '**NO**'} |")
w()
w("Leverage above ~70% fails a 1.30x minimum DSCR on base-case EBITDA. For a **cyclical commodity "
  "chemical** the right question is not the maximum a lender would sign at financial close but what "
  "survives a trough; Table 12 answers that.")
w()

w("## Table 11 — Sensitivity: investor economic ownership and shareholder loan coupon")
w()
w("Investor IRR (hold to Y15) / founder wealth Y15:")
w()
w("| Inv. equity % \\ SHL rate | 6% | 7% | 8% | 9% | 10% | 12% |")
w("|---|---|---|---|---|---|---|")
for ie in (0.25, 0.30, 0.35, 0.40, 0.45, 0.49):
    cells = []
    for rate in (0.06, 0.07, 0.08, 0.09, 0.10, 0.12):
        rr = run(BASE, rec(founder_econ=1-ie, shl_rate=rate))
        cells.append(f"{pct(rr['inv_irr_hold'])} / {num(rr['founder_wealth'](15,False),0)}")
    w(f"| **{ie:.0%}** | " + " | ".join(cells) + " |")
w()
w("Read down a column: every 5 points of economic ownership the founder concedes buys the investor "
  "roughly 0.6–0.8 points of IRR and costs the founder roughly 25–30 of terminal wealth. Read across "
  "a row: every 100bp on the shareholder loan buys the investor only ~0.15 points of IRR and costs "
  "the founder ~4. **Coupon is a far cheaper currency than equity.** Pay up on the coupon; defend "
  "the equity.")
w()

# ---------------------------------------------------------------- Table 12 stress
w("## Table 12 — Downside stress: the tests that actually decide the structure")
w()
w(f"Senior debt held constant at the base-case {num(R['senior'])} in every row — a stress test must "
  f"hold the capital structure fixed, not re-size the debt to the stressed cash flow.")
w()
w("| Scenario | Min DSCR | Lock-up yrs | Inv. IRR | Inv. MOIC | Founder wealth Y15 | Covers debt service? |")
w("|---|---:|---:|---:|---:|---:|:--:|")
scen = [
    ("Base case", BASE),
    ("Capex overrun +10%", replace(BASE, capex_overrun=0.10)),
    ("Capex overrun +20%", replace(BASE, capex_overrun=0.20)),
    ("Capex overrun +30%", replace(BASE, capex_overrun=0.30)),
    ("EBITDA -15%", replace(BASE, ebitda_stress=-0.15)),
    ("EBITDA -25%", replace(BASE, ebitda_stress=-0.25)),
    ("EBITDA -40%", replace(BASE, ebitda_stress=-0.40)),
    ("Delay 12 months", replace(BASE, delay_years=1)),
    ("Delay 24 months", replace(BASE, delay_years=2)),
    ("Overrun +20% AND EBITDA -25%", replace(BASE, capex_overrun=0.20, ebitda_stress=-0.25)),
    ("Overrun +20%, EBITDA -25%, delay 12m", replace(BASE, capex_overrun=0.20, ebitda_stress=-0.25, delay_years=1)),
]
BASE_SENIOR = R['senior']   # hold the capital structure FIXED across all stresses
for lbl, pr in scen:
    rr = run(pr, rec(fixed_senior=BASE_SENIOR))
    surv = rr['min_dscr'] and rr['min_dscr'] >= 1.00
    w(f"| {lbl} | {num(rr['min_dscr'],2)} | {rr['lockup_years']} | {pct(rr['inv_irr_hold'])} | "
      f"{num(rr['inv_moic_hold'],2)} | {num(rr['founder_wealth'](15,False))} | "
      f"{'yes' if surv else '**NO**'} |")
w()
w("The combined stress — a 20% overrun, a 25% EBITDA miss and a year's delay, all of which are "
  "*ordinary* on a brownfield chemical restart — is the case the whole structure must be built "
  "around. It is also the case in which a naive equity-cure clause converts the founder from "
  "majority to minority. Section I of the study is the answer.")
w()

# ---------------------------------------------------------------- Table 13
w("## Table 13 — Cost overrun: who pays, and what it does to the founder's stake")
w()
w("Overrun of 20% on 200 capex = 40 of extra funding. Effect on founder ownership under each mechanism:")
w()
w("| Mechanism | Extra founder cash | Extra investor cash | Founder stake after | Founder stake lost |")
w("|---|---:|---:|---:|---:|")
base_stake = 0.60
overrun = 40.0
R20 = run(replace(BASE, capex_overrun=0.20), rec())
pre_money = max(0.0, R['equity_value'](5))
w(f"| 1. Contingency reserve (pre-funded in the 233) | 0 | 0 | {base_stake:.1%} | 0.0 pts |")
w(f"| 2. EPC lump-sum turnkey wrap absorbs it | 0 | 0 | {base_stake:.1%} | 0.0 pts |")
w(f"| 3. Standby senior / ECA tranche | 0 | 0 | {base_stake:.1%} | 0.0 pts |")
w(f"| 4. Pro-rata subordinated overrun loan (non-dilutive) | 0 | {num(overrun)} | {base_stake:.1%} | 0.0 pts |")
inv_new = (1-base_stake) * pre_money + overrun
fdr_new_val = base_stake * pre_money
diluted = fdr_new_val / (fdr_new_val + inv_new) if (fdr_new_val+inv_new)>0 else 0
w(f"| 5. Investor funds as **new equity at the original valuation** | 0 | {num(overrun)} | "
  f"{diluted:.1%} | **{(base_stake-diluted)*100:.1f} pts** |")
inv_new_d = (1-base_stake) * pre_money*0.7 + overrun
fdr_new_d = base_stake * pre_money*0.7
dil2 = fdr_new_d / (fdr_new_d + inv_new_d) if (fdr_new_d+inv_new_d)>0 else 0
w(f"| 6. Investor funds as new equity at a **30% discounted** valuation (punitive) | 0 | "
  f"{num(overrun)} | {dil2:.1%} | **{(base_stake-dil2)*100:.1f} pts** |")
w()
w(f"Mechanism 5 — the market default an investor will propose — costs the founder "
  f"**{(base_stake-diluted)*100:.0f} percentage points of the company for a 20% overrun**, and "
  f"mechanism 6 costs {(base_stake-dil2)*100:.0f} points. That is the single largest ownership risk "
  f"in the entire transaction, larger than the opening negotiation over 51% vs 60%. Mechanisms 1–4 "
  f"cost zero. **The overrun waterfall is worth more negotiating effort than the headline split.**")
w()

# ---------------------------------------------------------------- Table 14
w("## Table 14 — Investor target IRR vs. what this asset can pay")
w()
w("| Investor type | Typical target IRR | Achievable here (hold) | Gap | Structurally compatible? |")
w("|---|---:|---:|---:|:--:|")
ach = R['inv_irr_hold']
for lbl, tgt in (("Large-cap buyout PE", 0.18), ("Mid-market PE", 0.20),
                 ("Distressed / opportunistic", 0.22), ("Industrial turnaround", 0.20),
                 ("Growth equity minority", 0.18), ("Mezzanine / private credit", 0.15),
                 ("Infrastructure equity (core-plus)", 0.12), ("Infrastructure (value-add)", 0.14),
                 ("Family office / permanent capital", 0.11), ("Strategic industrial", 0.12),
                 ("Sovereign / development capital", 0.10)):
    gap = ach - tgt
    ok = gap >= -0.015
    w(f"| {lbl} | {tgt:.0%} | {pct(ach)} | {gap:+.1%} | {'**YES**' if ok else 'no'} |")
w()
w("This single table determines who to call. Approaching Apollo, KKR or Oaktree with this asset at "
  "this EBITDA is a guaranteed rejection — not because the founder asked for too much control, but "
  "because the asset cannot pay their cost of capital at any split. The compatible universe is "
  "infrastructure / value-add funds, family offices, strategics with an offtake motive, and "
  "ECA-supported Chinese industrial capital.")
w()

open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "MODEL-OUTPUTS.md"), "w").write(OUT.getvalue())
print(OUT.getvalue()[:1500])
print("...")
print(f"\n[written: {len(OUT.getvalue())} chars]")
